 version: '3.5'

 services:
   dbclient:
      image: alpine
      networks:
        - galera_network
      environment:
        - BACKUP_ENABLED=1
        - BACKUP_INTERVAL=3600
        - BACKUP_PATH=/data
        - BACKUP_FILENAME=db_backup
      entrypoint: |
         sh -c 'sh -s << EOF
         apk add --no-cache mysql-client
         while true
           do
             if [ $$BACKUP_ENABLED == 1 ]
             then
               sleep $$BACKUP_INTERVAL
               mkdir -p $$BACKUP_PATH/$$(date +%F)
               echo "$$(date +%FT%H.%m) - Making Backup to : $$BACKUP_PATH/$$(date +%F)/$$BACKUP_FILENAME-$$(date +%FT%H.%m).sql.gz"
               mysqldump -u root -ppassword -h maxscale --all-databases | gzip > $$BACKUP_PATH/$$(date +%F)/$$BACKUP_FILENAME-$$(date +%FT%H.%m).sql.gz
               find $$BACKUP_PATH -mtime 7 -delete
             fi
           done
         EOF' 
      volumes:
         - vol_dbclient:/data
      deploy:
        mode: replicated
        replicas: 1
        placement:
           constraints:
            - node.role==manager

   galera_cluster:
       image: toughiq/mariadb-cluster
       environment:
          DB_SERVICE_NAME: "galera_cluster"
          MYSQL_ROOT_PASSWORD: "password"
          MYSQL_DATABASE: "prueba"
          MYSQL_USER: "user"
          MYSQL_PASSWORD: "password"
       networks:
         - galera_network
       deploy:
          mode: replicated
          replicas: 1
          placement:
            constraints:
               - node.role==worker

   maxscale:
      image: toughiq/maxscale
      ports:
        - 3306:3306
      environment:
        - DB_SERVICE_NAME=galera_cluster
        - ENABLE_ROOT_USER=1
      networks:
        - galera_network 
      deploy:
         mode: replicated
         replicas: 1
         placement:
            constraints:
             - node.role==manager
     
 volumes:
    vol_dbclient:
       driver: local         
 networks:
   galera_network:
     name: galera_network
     driver: overlay 